services:
  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: asdf
      POSTGRES_DB: graphql_api
    ports:
      - "5432:5432"
    volumes:
      - graphql_db_data:/var/lib/postgresql/data # Mount volume for persistent storage

volumes:
  graphql_db_data:
    driver: local